services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  test_db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend
    ports:
      - '5433:5432'
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend:
