# Generated by Django 5.1.6 on 2025-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
