# Generated by Django 5.1.6 on 2025-02-22 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.PositiveSmallIntegerField(
                verbose_name="Номер столика"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="dish",
            field=models.CharField(
                max_length=256, verbose_name="Название блюда"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Стоймость"
            ),
        ),
    ]
