# Generated by Django 5.1.6 on 2025-02-23 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0002_orderitem_quantity_alter_order_table_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PG", "в ожидании"),
                    ("RD", "готово"),
                    ("PD", "оплачено"),
                ],
                default="PG",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="Номер стола"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Полная стоймость",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
                verbose_name="Cтоймость",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["table_number"], name="orders_orde_table_n_63e048_idx"
            ),
        ),
    ]
