# Generated by Django 5.1.6 on 2025-02-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0005_alter_order_table_number_alter_orderitem_dish_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.PositiveIntegerField(
                error_messages={
                    "unique": "Стол с таким номером уже существует. Пожалуйста, выберите другой номер."
                },
                unique=True,
                verbose_name="Номер стола",
            ),
        ),
    ]
