# Generated by Django 5.1.6 on 2025-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_table_number"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_table_n_63e048_idx",
        ),
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.PositiveIntegerField(verbose_name="Номер стола"),
        ),
    ]
