# Generated by Django 5.1.6 on 2025-02-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0007_remove_order_orders_orde_table_n_63e048_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-status", "-created_at"),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "в ожидании"),
                    ("2", "готово"),
                    ("3", "оплачено"),
                ],
                default="1",
                max_length=1,
                verbose_name="Статус",
            ),
        ),
    ]
