# Generated by Django 5.1.6 on 2025-02-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_search_vector_order_status_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Элемент заказа",
                "verbose_name_plural": "Элемент заказа",
            },
        ),
    ]
