name: Django CI

on: [ push ]

env:
  PYTHONPATH: src
  SECRET_KEY: secret

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v4

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: 2.14.2

      - name: Run test server
        run: |
          docker compose -f docker-compose.dev.yml up -d

      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run End-To-End tests
        run: |
          poetry run poe test